version: '3'
services:
  db:
    image: mariadb:5
    restart: always
    volumes : 
      - mariadb:/var/lib/mysql"
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=userpw
      - MYSQL_DATABASE=wordpress
      - MYSQL_ROOT_PASSWORD=rootroot
  dbadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=userpw
      - MYSQL_DATABASE=wordpress
      - MYSQL_ROOT_PASSWORD=rootroot
      - PMA_HOST=db
    depends_on:
      - db

  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    ports:
      - "8000:80"
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=user
      - WORDPRESS_DB_PASSWORD=userpw
      - WORDPRESS_DB_NAME=wordpress

volumes:
  mariadb:
